Задание №1

In [2]:
import cv2
import numpy as np

In [55]:
# Загрузка изображения
image = cv2.imread('line5.jpg')

# Преобразование изображения в оттенки серого
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Применение Гауссова размытия для уменьшения шума и улучшения обнаружения границ
gray = cv2.GaussianBlur(gray, (5, 5), 0)

# Обнаружение границ с помощью детектора границ Canny
edges = cv2.Canny(gray, 50, 150, apertureSize=3)

# Использование преобразования Хафа для обнаружения линий
# 1 - разрешение расстояния в пространстве Хафа в пикселях
# np.pi / 180 - разрешение угла в пространстве Хафа в радианах
# 100 - пороговое значение для принятия линии
lines = cv2.HoughLines(edges, 1, np.pi / 180, 200)

# Отрисовка линий на исходном изображении
for line in lines:
    rho, theta = line[0]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a * rho
    y0 = b * rho
    x1 = int(x0 + 1000 * (-b))
    y1 = int(y0 + 1000 * (a))
    x2 = int(x0 - 1000 * (-b))
    y2 = int(y0 - 1000 * (a))
    cv2.line(image, (x1, y1), (x2, y2), (255, 255, 255), 14)

# Отображение результата
cv2.imshow('Hough Lines', image)
cv2.imshow('ISH', gray)
cv2.imshow('edges', edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

Задание №2

In [56]:
path = r"./res_circ.jpg"
pic = cv2.imread(path, cv2.IMREAD_COLOR)
#b, r, g = cv2.split(pic)
#pic = cv2.merge([b,r,g])
pic_g = cv2.imread(path, cv2.IMREAD_GRAYSCALE) 
pic_f = cv2.GaussianBlur(255 - pic_g,(3,3),0)
a = pic.shape[0]
circles = cv2.HoughCircles(pic_g, cv2.HOUGH_GRADIENT, 1, minDist = a//20, param1 = 100, param2 = 50, minRadius = a//1000, maxRadius = a//2) 
print(circles[0])
max_radius = 0
for circle in circles[0]:
    center = int(circle[0]), int(circle[1])
    radius = int(circle[2])
    if max_radius < radius: max_radius = radius 
    cv2.circle(pic, center, radius, (0, 0, 255), 3) 
cv2.imshow('result', pic)
cv2.imshow('original', pic_g)
cv2.imshow('pic_f', pic_f)
print(f"Максимальный радиус равен {max_radius}")
cv2.waitKey(0)
cv2.destroyAllWindows()

[[106.5 412.5  48.3]
 [183.5 284.5  54.6]
 [221.5  99.5  29.3]
 [ 79.5 100.5  47.4]]
Максимальный радиус равен 54


In [59]:
path = r"./res_circ.jpg"
image = cv2.imread(path)

# Преобразование изображения в оттенки серого
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#gray_inv = cv2.bitwise_not(gray)

# Применение Гауссова размытия для уменьшения шума
blurred = cv2.GaussianBlur(gray, (5, 5), 0)
# Обнаружение границ с помощью детектора границ Canny
edges = cv2.Canny(blurred, 50, 150, apertureSize=3)

# Использование Probabilistic Hough Transform для обнаружения линий
# 1 и np.pi / 180 - разрешение в пространстве Хафа (расстояние и угол)
# 50 - минимальная длина линии
# 10 - максимальное разрыв между сегментами линии для считывания их за одну линию
lines = cv2.HoughLinesP(edges, 1, np.pi / 180, threshold=50, minLineLength=30, maxLineGap=5)

# Отрисовка линий на исходном изображении
max_len = 0
for num, line in enumerate(lines):
    #print(f"{num} {line[0]}")
    x1, y1, x2, y2 = line[0]
    len = np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
    if max_len < len: max_len = len
    cv2.line(image, (x1, y1), (x2, y2), (0, 255, 0), 2)

# Отображение результата
cv2.imshow('Probabilistic Hough Lines', image)
cv2.imshow('edges', edges)
#cv2.imshow('gray_inv', gray_inv)
cv2.imshow('gray', gray)
print(f"Максимальная длина отрезка: {max_len}")
cv2.waitKey(0)
cv2.destroyAllWindows()


Максимальная длина отрезка: 311.4113035841827


Задание №3

In [60]:
path = r"./4_5_1.jpg"
pic = cv2.imread(path, cv2.IMREAD_REDUCED_COLOR_8)
#b, r, g = cv2.split(pic)
#pic = cv2.merge([b,r,g])
pic_g = cv2.imread(path, cv2.IMREAD_REDUCED_GRAYSCALE_8) 
pic_f = cv2.GaussianBlur(255 - pic_g,(3,3),0)
a = pic.shape[0]
circles = cv2.HoughCircles(pic_g, cv2.HOUGH_GRADIENT, 1, minDist = a//20, param1 = 100, param2 = 50, minRadius = a//1000, maxRadius = a//15) 
print(circles[0])
for circle in circles[0]:
    center = int(circle[0]), int(circle[1])
    radius = int(circle[2])
    cv2.circle(pic, center, radius, (0, 0, 255), 3) 
cv2.imshow('result', pic)
cv2.imshow('original', pic_g)
cv2.imshow('pic_f', pic_f)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[158.5 263.5  38.2]]


In [62]:
import cv2
path = r"./4_5_2.jpg"
pic = cv2.imread(path, cv2.IMREAD_REDUCED_COLOR_8)
pic_g = cv2.imread(path, cv2.IMREAD_REDUCED_GRAYSCALE_8) 
pic_f = cv2.GaussianBlur(255 - pic_g,(3,3),0)
a = pic.shape[0]
circles = cv2.HoughCircles(pic_g, cv2.HOUGH_GRADIENT, 1, minDist = a//20, param1 = 100, param2 = 50, minRadius = a//5, maxRadius = a//4) 
print(circles[0])
for circle in circles[0]:
    center = int(circle[0]), int(circle[1])
    radius = int(circle[2])
    cv2.circle(pic, center, radius, (0, 0, 255), 3) 
cv2.imshow('result', pic)
cv2.imshow('original', pic_g)
cv2.imshow('pic_f', pic_f)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[369.5 232.5 121.1]]


In [63]:
import cv2
path = r"./4_5_3.jpg"
pic = cv2.imread(path, cv2.IMREAD_REDUCED_COLOR_8)
#b, r, g = cv2.split(pic)
#pic = cv2.merge([b,r,g])
pic_g = cv2.imread(path, cv2.IMREAD_REDUCED_GRAYSCALE_8) 
pic_f = cv2.GaussianBlur(255 - pic_g,(3,3),0)
a = pic.shape[0]
circles = cv2.HoughCircles(pic_g, cv2.HOUGH_GRADIENT, 1, minDist = a//20, param1 = 100, param2 = 50, minRadius = a//10, maxRadius = a//5) 
print(circles[0])
for circle in circles[0]:
    center = int(circle[0]), int(circle[1])
    radius = int(circle[2])
    cv2.circle(pic, center, radius, (0, 0, 255), 3) 
cv2.imshow('result', pic)
cv2.imshow('original', pic_g)
cv2.imshow('pic_f', pic_f)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[189.5 252.5 111.2]]


Задание №4

In [64]:
import cv2
import numpy as np
path = r"./6-1.png"
def contourRecogniton(contour, maxDiff):
    contourArea = cv2.contourArea(contour=contour)
    c, r = cv2.minEnclosingCircle(contour)
    circArea = np.pi * r**2
    rect = cv2.boundingRect(contour)
    x,y,w,h = rect
    rectArea = w * h
    if abs(contourArea - circArea) <= maxDiff:
        return "Окружность"
    if abs(contourArea - rectArea) <= maxDiff:
        return "Прямоугольник"
    else:
        return "Треугольник"
picture =cv2.imread(path,cv2.IMREAD_COLOR)
gray = cv2.cvtColor(picture,cv2.COLOR_BGR2GRAY)
gray = cv2.bitwise_not(gray)
res = cv2.findContours(gray,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
contours, hierarchy = res
cv2.drawContours(image=picture, contours=contours, contourIdx=2,color=100,thickness=5)
for index,contour in enumerate(contours):
    contourType = contourRecogniton(contour,1500)
    match contourType:
        case "Окружность":
            cv2.drawContours(image=picture, contours=contours, contourIdx=index,color=(255,0,0),thickness=5)
        case "Прямоугольник":
             cv2.drawContours(image=picture, contours=contours, contourIdx=index,color=(0,0,255),thickness=5)
        case "Треугольник":
             cv2.drawContours(image=picture, contours=contours, contourIdx=index,color=(255,0,127),thickness=5)         
cv2.imshow("picture", picture)
cv2.waitKey(0)
cv2.destroyAllWindows()